

services:
  llm_service:
    image: ollama/ollama
    hostname: llm_service
    container_name: llm_service
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - llmdata:/root/.ollama:rw
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          memory: 6g
        reservations:
          memory: 5g

  llm_service_init:
    image: curlimages/curl:latest
    container_name: llm_service-init
    depends_on:
      - llm_service
    volumes:
      - ./scripts/init_ollama.sh:/init_ollama.sh:ro
    entrypoint: ["/bin/sh", "/init_ollama.sh"]
    environment:
      - LLM_MODEL=${LLM_MODEL:-tinyllama}
    
  security_service:
    container_name: security_service
    hostname: security_service
    image: openpolicyagent/opa:latest
    ports:
      - "127.0.0.1:8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=debug"           
      - "--log-format=json-pretty" 
      - "/policies"
    volumes:
      - $PWD/policies:/policies:ro
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"

  proxy_service:
    image: nginx-opa-llm-prompt-check:latest
    container_name: proxy_service
    hostname: proxy_service
    volumes:
      - $PWD/config/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - $PWD/config/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - security_service
      - llm_service

  metrics_service:
    hostname: metrics_service
    container_name: metrics_service
    image: prom/prometheus:latest
    volumes:
      - $PWD/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"

  metrics_service_dashboard:
    hostname: metrics_service_dashboard
    container_name: metrics_service_dashboard
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - $PWD/config/grafana/dashboards:/var/lib/grafana/dashboards
      - $PWD/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
volumes:
  llmdata: